import {
	IoSearchOutline,
	IoSearchSharp,
	IoCallOutline,
	IoVideocamOutline,
	IoInformationCircleOutline,
	IoChatbubblesOutline,
	IoArrowBack,
	IoArrowUp,
	IoArrowForward,
	IoLocationOutline,
	IoClose,
	IoContrast,
	IoChevronBack,
	IoChevronForward,
	IoNotificationsOutline,
	IoPerson,
	IoArrowBackCircleOutline,
	IoArrowForwardCircleOutline,
	IoVideocam,
	IoVideocamOff,
} from "react-icons/io5";
import {
	MdOutlineExplore,
	MdExplore,
	MdCropRotate,
	MdCropPortrait,
	MdCropDin,
	MdCrop32,
	MdOutlineGridOn,
	MdOutlineAddCircleOutline,
	MdOutlineWaterDrop,
	MdNavigateNext,
	MdNavigateBefore,
	MdMoreHoriz,
	MdMoreVert,
	MdOutlineAccountBox,
	MdMenu,
	MdMenuOpen,
	MdFiberManualRecord,
	MdBlockFlipped,
	MdVisibility,
	MdVisibilityOff,
	MdLock,
	MdEdit,
	MdCallEnd,
} from "react-icons/md";
import { BiMoviePlay, BiSolidMoviePlay, BiBrush } from "react-icons/bi";
import {
	RiAddBoxLine,
	RiAddBoxFill,
	RiAccountCircleLine,
	RiAccountCircleFill,
	RiHome4Fill,
	RiHome4Line,
	RiChat3Fill,
	RiChat3Line,
	RiChat1Fill,
	RiChat1Line,
	RiBookmarkLine,
	RiBookmarkFill,
	RiLinkM,
	RiDislikeLine,
	RiChatOffLine,
} from "react-icons/ri";
import {
	IoMdImages,
	IoIosArrowDown,
	IoIosArrowUp,
	IoIosAddCircle,
	IoMdTrash,
	IoIosSquare,
	IoIosSettings,
	IoMdLogOut,
	IoMdExpand,
	IoMdMic,
	IoMdMicOff,
} from "react-icons/io";
import {
	LuSend,
	LuReply,
	LuMic,
	LuFlipHorizontal2,
	LuCrop,
	LuFlipVertical2,
	LuCloudy,
	LuPlus,
	LuTrash,
	LuSmile,
	LuHeartOff,
	LuSendHorizonal,
	LuScreenShare,
} from "react-icons/lu";
import { FaRegImage, FaImages, FaPlay, FaPause } from "react-icons/fa6";
import {
	TbBoxMultiple,
	TbZoomIn,
	TbArrowBackUp,
	TbMessageReport,
} from "react-icons/tb";
import { LiaPhotoVideoSolid } from "react-icons/lia";
import {
	BsBrightnessHigh,
	BsThermometerHalf,
	BsVignette,
	BsPeople,
	BsPersonAdd,
} from "react-icons/bs";
import { SiTicktick } from "react-icons/si";
import { GrAttachment } from "react-icons/gr";
import {
	FaRegCopy,
	FaWhatsapp,
	FaCheckCircle,
	FaRegCircle,
} from "react-icons/fa";
import { HiDownload } from "react-icons/hi";
import { FiShare, FiLock } from "react-icons/fi";
import { AiOutlineHeart, AiFillHeart } from "react-icons/ai";


const ReactIcons = {
	IoSearchOutline,
	IoSearchSharp,
	MdOutlineExplore,
	MdExplore,
	BiMoviePlay,
	BiSolidMoviePlay,
	RiChat3Fill,
	RiChat3Line,
	RiAddBoxLine,
	RiAddBoxFill,
	RiAccountCircleLine,
	RiAccountCircleFill,
	RiHome4Fill,
	RiHome4Line,
	AiOutlineHeart,
	AiFillHeart,
	RiChat1Fill,
	RiChat1Line,
	LuSend,
	RiBookmarkLine,
	RiBookmarkFill,
	LuReply,
	LuMic,
	FaRegImage,
	IoMdImages,
	IoCallOutline,
	IoVideocamOutline,
	IoInformationCircleOutline,
	IoChatbubblesOutline,
	TbBoxMultiple,
	TbZoomIn,
	MdCropRotate,
	MdCropPortrait,
	MdCropDin,
	MdCrop32,
	LuFlipHorizontal2,
	LuCrop,
	LuFlipVertical2,
	IoArrowBack,
	IoArrowUp,
	LiaPhotoVideoSolid,
	IoLocationOutline,
	IoIosArrowDown,
	IoIosArrowUp,
	IoClose,
	MdOutlineGridOn,
	MdOutlineAddCircleOutline,
	IoArrowForward,
	BsBrightnessHigh,
	IoContrast,
	LuCloudy,
	MdOutlineWaterDrop,
	BsThermometerHalf,
	BsVignette,
	SiTicktick,
	MdNavigateBefore,
	MdNavigateNext,
	IoIosAddCircle,
	IoChevronBack,
	MdMoreHoriz,
	MdOutlineAccountBox,
	FaImages,
	MdMenu,
	MdMenuOpen,
	MdFiberManualRecord,
	LuPlus,
	FaPlay,
	FaPause,
	GrAttachment,
	IoMdTrash,
	IoIosSquare,
	MdMoreVert,
	FaRegCopy,
	LuTrash,
	LuSmile,
	RiLinkM,
	FaWhatsapp,
	HiDownload,
	FiShare,
	FaCheckCircle,
	FaRegCircle,
	IoIosSettings,
	IoNotificationsOutline,
	FiLock,
	MdBlockFlipped,
	RiDislikeLine,
	IoChevronForward,
	IoMdLogOut,
	MdVisibility,
	MdVisibilityOff,
	IoPerson,
	MdLock,
	MdEdit,
	LuHeartOff,
	RiChatOffLine,
	LuSendHorizonal,
	IoArrowBackCircleOutline,
	IoArrowForwardCircleOutline,
	TbArrowBackUp,
	BiBrush,
	BsPeople,
	BsPersonAdd,
	TbMessageReport,
	IoMdExpand,
	LuScreenShare,
	IoVideocam,
	IoVideocamOff,
	IoMdMic,
	IoMdMicOff,
	MdCallEnd,
};

export default ReactIcons;
