import {
	IoSearchOutline,
	IoSearchSharp,
	IoCallOutline,
	IoVideocamOutline,
	IoInformationCircleOutline,
	IoChatbubblesOutline,
	IoArrowBack,
	IoArrowForward,
	IoLocationOutline,
	IoClose,
	IoContrast,
	IoChevronBack,
} from "react-icons/io5";
import {
	MdOutlineExplore,
	MdExplore,
	MdCropRotate,
	MdCropPortrait,
	MdCropDin,
	MdCrop32,
	MdOutlineGridOn,
	MdOutlineAddCircleOutline,
	MdOutlineWaterDrop,
	MdNavigateNext,
	MdNavigateBefore,
	MdMoreHoriz,
	MdOutlineAccountBox,
} from "react-icons/md";
import { BiMoviePlay, BiSolidMoviePlay } from "react-icons/bi";
import {
	RiAddBoxLine,
	RiAddBoxFill,
	RiAccountCircleLine,
	RiAccountCircleFill,
	RiHome4Fill,
	RiHome4Line,
	RiChat3Fill,
	RiChat3Line,
	RiHeart3Line,
	RiHeart3Fill,
	RiChat1Fill,
	RiChat1Line,
	RiBookmarkLine,
	RiBookmarkFill,
} from "react-icons/ri";
import { IoMdImages, IoIosArrowDown } from "react-icons/io";
import {
	LuSend,
	LuReply,
	LuMic,
	LuFlipHorizontal2,
	LuCrop,
	LuFlipVertical2,
	LuCloudy,
} from "react-icons/lu";
import { FaRegImage, FaImages } from "react-icons/fa6";
import { TbBoxMultiple, TbZoomIn } from "react-icons/tb";
import { LiaPhotoVideoSolid } from "react-icons/lia";
import {
	BsBrightnessHigh,
	BsThermometerHalf,
	BsVignette,
} from "react-icons/bs";
import { SiTicktick } from "react-icons/si";
import { IoIosAddCircle } from "react-icons/io";



const ReactIcons = {
	IoSearchOutline,
	IoSearchSharp,
	MdOutlineExplore,
	MdExplore,
	BiMoviePlay,
	BiSolidMoviePlay,
	RiChat3Fill,
	RiChat3Line,
	RiAddBoxLine,
	RiAddBoxFill,
	RiAccountCircleLine,
	RiAccountCircleFill,
	RiHome4Fill,
	RiHome4Line,
	RiHeart3Line,
	RiHeart3Fill,
	RiChat1Fill,
	RiChat1Line,
	LuSend,
	RiBookmarkLine,
	RiBookmarkFill,
	LuReply,
	LuMic,
	FaRegImage,
	IoMdImages,
	IoCallOutline,
	IoVideocamOutline,
	IoInformationCircleOutline,
	IoChatbubblesOutline,
	TbBoxMultiple,
	TbZoomIn,
	MdCropRotate,
	MdCropPortrait,
	MdCropDin,
	MdCrop32,
	LuFlipHorizontal2,
	LuCrop,
	LuFlipVertical2,
	IoArrowBack,
	LiaPhotoVideoSolid,
	IoLocationOutline,
	IoIosArrowDown,
	IoClose,
	MdOutlineGridOn,
	MdOutlineAddCircleOutline,
	IoArrowForward,
	BsBrightnessHigh,
	IoContrast,
	LuCloudy,
	MdOutlineWaterDrop,
	BsThermometerHalf,
	BsVignette,
	SiTicktick,
	MdNavigateBefore,
	MdNavigateNext,
	IoIosAddCircle,
	IoChevronBack,
	MdMoreHoriz,
	MdOutlineAccountBox,
	FaImages,
};

export default ReactIcons;
